sudo: required
services:
  - docker
language: rust
install:
  - curl -sL https://taskfile.dev/install.sh | sh
script:
  - |
    if [ "$TRAVIS_BRANCH" = "master" ] && [ "$TRAVIS_PULL_REQUEST" = "false" ];
      then
      echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      ./bin/task build push;
    fi
