# Use postgres/example user/password credentials
version: "3.1"

services:
  yaps:
    image: southclaws/yaps
    environment:
      ROCKET_DATABASES: '{yaps={url="postgres://yaps:${POSTGRES_PASSWORD}@db/yaps?sslmode=disable"}}'
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_USER: yaps
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: yaps
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - 8081:80
