version: "2"

vars:
  OWNER: southclaws
  SERVICE: yaps
  GIT_COMMIT: { sh: git describe --always --dirty --tags }

tasks:
  migrations:
    cmds:
      - diesel migrations run
  build:
    cmds:
      - docker build -t southclaws/yaps:{{ .GIT_COMMIT }} .
  run:
    cmds:
      - docker run --env-file=.env --entrypoint=/yaps southclaws/yaps:{{ .GIT_COMMIT }}
  push:
    cmds:
      - docker push {{.OWNER}}/{{.SERVICE}}:{{.GIT_COMMIT}}
      - docker tag {{.OWNER}}/{{.SERVICE}}:{{.GIT_COMMIT}} {{.OWNER}}/{{.SERVICE}}:latest
      - docker push {{.OWNER}}/{{.SERVICE}}:latest
